<?php
	define('HOSTNAME','http://127.0.0.1/php-micro-framework/');
	define('PROJECTPATH','D:/wamp/www/php-micro-framework/admin/');
	define('ENGINE','D:/wamp/www/php-micro-framework/engine/');
	define('UPLOAD','D:/wamp/www/php-micro-framework/upload/');
	define('SERVERNAME','localhost');
	define('DBNAME','zjh');
	define('USERNAME','root');
	define('PASSWORD','');
	define('MODEL',PROJECTPATH.'model/');
	define('CONTROLLER',PROJECTPATH.'controller/');
	define('VIEW',PROJECTPATH.'view/');
	define('ENGINE',PROJECTPATH.'engine/');
?>